/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ScHeroBanner {
        "backgroundColour"?: string;
        "fontSize"?: string;
        "headingLevel"?: number;
        /**
          * Horizontal position.
         */
        "horizontalPosition": string;
        "spacing"?: string;
        /**
          * Hero text.
         */
        "text": string;
        "textAlign"?: string;
        "textColour"?: string;
        /**
          * Vertical position.
         */
        "verticalPosition": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLScHeroBannerElement extends Components.ScHeroBanner, HTMLStencilElement {
    }
    var HTMLScHeroBannerElement: {
        prototype: HTMLScHeroBannerElement;
        new (): HTMLScHeroBannerElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sc-hero-banner": HTMLScHeroBannerElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ScHeroBanner {
        "backgroundColour"?: string;
        "fontSize"?: string;
        "headingLevel"?: number;
        /**
          * Horizontal position.
         */
        "horizontalPosition"?: string;
        "spacing"?: string;
        /**
          * Hero text.
         */
        "text"?: string;
        "textAlign"?: string;
        "textColour"?: string;
        /**
          * Vertical position.
         */
        "verticalPosition"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sc-hero-banner": ScHeroBanner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sc-hero-banner": LocalJSX.ScHeroBanner & JSXBase.HTMLAttributes<HTMLScHeroBannerElement>;
        }
    }
}
