/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StrawberryHeroBanner {
        /**
          * Image src.
         */
        "image": string;
        /**
          * Image Alt Text.
         */
        "imageAlt": string;
        /**
          * Hero text.
         */
        "text": string;
        "vertical_position": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStrawberryHeroBannerElement extends Components.StrawberryHeroBanner, HTMLStencilElement {
    }
    var HTMLStrawberryHeroBannerElement: {
        prototype: HTMLStrawberryHeroBannerElement;
        new (): HTMLStrawberryHeroBannerElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "strawberry-hero-banner": HTMLStrawberryHeroBannerElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StrawberryHeroBanner {
        /**
          * Image src.
         */
        "image"?: string;
        /**
          * Image Alt Text.
         */
        "imageAlt"?: string;
        /**
          * Hero text.
         */
        "text"?: string;
        "vertical_position"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "strawberry-hero-banner": StrawberryHeroBanner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "strawberry-hero-banner": LocalJSX.StrawberryHeroBanner & JSXBase.HTMLAttributes<HTMLStrawberryHeroBannerElement>;
        }
    }
}
